name: NPM Publish new version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.0]

    steps:
      - uses: actions/checkout@v2
      - name: Prepare Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: NPM login
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
